travis:
  secure:
    BINSTAR_TOKEN: O0Rh1DqbofJvgpIE6h0YeJwIaGzJmIkJU9M70EPRXtBLyxhTvf0p0LSkTGJuQ2mQZx9DnKeLjL9KCHADhQjTZlNSeYjwZfU2EcpnIhAJWs8B1BndlLCa0He8NGmkBE4aE8xWhkeAuFrup0mJX4oKpDYM6whhWQijVkbo+eGcEzGY70+QBGWn5q0o4bQhaFGGOL1ARl4E9zexWmv9WmgBBWGES1rr7jlTaoBklPsDHLNSyVrpYc8+OqjtjoMtGECuPoizw2ATSv9wtLBAzH7F57N15FtGDPvioCaq62v+0j5AVh0YpNyUnKg76B2w1guHbapgRm1AtxfAHlQNSuZepXhjj2H2kcVA1k4qsD3wv+Gkh/NTt/xwoVufliYT+ac909XZIpA+xq32S8wG5Osdv8xHdp7ImQdmZEgTn76CjUMmLrm2xptw3V0DB+hn54Wcx60BwTVjBZ5/XSidDHXxJVbi1B6sSqHAHCtjjNq7RN0ShwPZBEI1HVcT0DJbXMa5RTVybNAEwQNJV4nBkVMemMrFxGP29M8LrSX+S5D3nvsDjy+/pTgqfVY/KxyiBGKddQ7FE5CqlBJik/alOARaoIASkJJsUw83lbdtzBeKCjquzxu2nrDRcTy0/NfCDQRuCfQt+SpxU/CJvtni9MRDRRYh10wx300WQywt9LL9ehI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
